;;;; data.import.scm - GENERATED BY CHICKEN 4.8.0.4 -*- Scheme -*-

(eval '(import
         chicken
         scheme
         extras
         medea
         unix-sockets
         ports
         srfi-18
         data-structures))
(##sys#register-compiled-module
  'data
  (list)
  '((update-track . data#update-track)
    (update-pattern . data#update-pattern)
    (make-default-pattern . data#make-default-pattern)
    (instrument-name . data#instrument-name)
    (instrument-note . data#instrument-note)
    (instrument-latency . data#instrument-latency)
    (instrument-steps . data#instrument-steps)
    (instrument-name-set! . data#instrument-name-set!)
    (instrument-note-set! . data#instrument-note-set!)
    (instrument-latency-set! . data#instrument-latency-set!)
    (instrument-steps-set! . data#instrument-steps-set!))
  (list)
  (list))

;; END OF FILE
