;;;; ipc.import.scm - GENERATED BY CHICKEN 4.8.0.4 -*- Scheme -*-

(eval '(import
         chicken
         scheme
         extras
         medea
         unix-sockets
         ports
         srfi-18
         data-structures))
(##sys#register-compiled-module
  'ipc
  (list)
  '((update-track . ipc#update-track)
    (make-default-pattern . ipc#make-default-pattern)
    (process-song-updates . ipc#process-song-updates))
  (list)
  (list))

;; END OF FILE
