;;;; ipc.import.scm - GENERATED BY CHICKEN 4.8.0.4 -*- Scheme -*-

(eval '(import
         chicken
         scheme
         extras
         medea
         unix-sockets
         ports
         srfi-18
         data-structures
         data))
(##sys#register-compiled-module
  'ipc
  (list)
  '((update-track . data#update-track)
    (update-pattern . data#update-pattern)
    (process-ipc-messages . ipc#process-ipc-messages))
  (list)
  (list))

;; END OF FILE
